stages:
  - empacotamento

variables: 
  ssh_user: root
  server: valentino
  repo_path: /srv/repo
  section: Misc
  package: committer
  priority: optional
  version: $CI_COMMIT_TAG
  architecture: amd64
  maintainer: "Hanokh Software Labs"
  depends: "git, certbot"
  Description: "Acessa pastas configuradas e faz commit das mudanças automaticamente"

Empacotamento:
  stage: empacotamento

  script:
    - test -d /tmp/"$package"/DEBIAN && rm -rf /tmp/"$package"
    - mkdir /tmp/$package
    - mkdir /tmp/"$package"/DEBIAN
    - echo "Section:$section" >> /tmp/"$package"/DEBIAN/control
    - echo "Package:$package" >> /tmp/"$package"/DEBIAN/control
    - echo "Priority:$priority" >> /tmp/"$package"/DEBIAN/control
    - echo "Version:$version" >> /tmp/"$package"/DEBIAN/control
    - echo "Architecture:$architecture" >> /tmp/"$package"/DEBIAN/control
    - echo "Maintainer:$maintainer" >> /tmp/"$package"/DEBIAN/control
    - echo "Depends:$depends" >> /tmp/"$package"/DEBIAN/control
    - echo "Description:$description" >> /tmp/"$package"/DEBIAN/control
    - echo  >> /tmp/"$package"/DEBIAN/control
    - echo "#!/bin/bash" >> /tmp/"$package"/DEBIAN/postinst
    - echo "test -h /usr/bin/committer || 
      ln -s /usr/share/committer/committer.py /usr/bin/committer" >> 
      /tmp/"$package"/DEBIAN/postinst
    
    - chmod +x /tmp/"$package"/DEBIAN/*
    - mkdir -p /tmp/"$package"/usr/share/committer
    - cp -av * /tmp/"$package"/usr/share/committer
    - dpkg -b /tmp/"$package" /tmp
    - ssh $ssh_user@$server "reprepro -b $repo_path includedeb hanokh /tmp/$package_$version_$architecture.deb"
  rules:
    - if: $CI_COMMIT_TAG
